site_name: Open Data Engineering Academy
site_url: https://yourusername.github.io/data-engineering-bootcamp/
repo_url: https://github.com/mckenzie-andrew/odea
repo_name: GitHub

theme:
  name: material
  logo: assets/odea.png
  favicon: material/database
  features:
    - navigation.tabs           # Top-level tabs for major phases
    - navigation.sections       # Expandable sidebar sections
    - navigation.top            # "Back to top" button
    - toc.integrate             # Table of contents inside the sidebar (cleaner)
    - content.code.copy         # Copy button on code blocks
    - content.tabs.link         # link tabs with same content
  palette: 
    # System preference default, but switchable
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode

# Extensions allow for the "Engineer" features like callouts and diagrams
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:     # Necessary for Mermaid Diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:          # Enables the Side-by-Side Code tabs
      alternate_style: true 
  - admonition                # Warning/Info blocks
  - pymdownx.details          # Collapsible blocks
  - attr_list

nav:
  - Home: index.md
  - "SQL for Data Engineers, I":
    - "0: Welcome": sql_for_data_engineers_part_one/0_table_of_contents.md
    - "1: Learn the Basics": sql_for_data_engineers_part_one/1_learn_the_basics.md
    - "2: Basic SQL Syntax": sql_for_data_engineers_part_one/2_basic_sql_syntax.md
    - "3: Data Definition Language (DDL)": sql_for_data_engineers_part_one/3_data_definition_language.md
    - "4: Data Manipulation Language (DML)": sql_for_data_engineers_part_one/4_data_manipulation_language.md
    - "5: Data Constraints": sql_for_data_engineers_part_one/5_data_constraints.md
    - "6: Aggregate Functions": sql_for_data_engineers_part_one/6_aggregate_functions.md


extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocs_quiz:
      auto_number: true