site_name: Open Data Engineering Academy
site_url: https://yourusername.github.io/data-engineering-bootcamp/
repo_url: https://github.com/mckenzie-andrew/odea
repo_name: GitHub

theme:
  name: material
  logo: assets/odea.png
  favicon: material/database
  features:
    - navigation.tabs
    #- navigation.sections
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.tabs.link
  palette: 
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - attr_list

nav:
  - Home: index.md
  - Databases and SQL:
    - databases_and_sql/index.md
    - Structured Query Language:
      - "0: Welcome": databases_and_sql/structured_query_language/0_table_of_contents.md
      - "1: Learn the Basics": databases_and_sql/structured_query_language/1_learn_the_basics.md
      - "2: Basic SQL Syntax": databases_and_sql/structured_query_language/2_basic_sql_syntax.md
      - "3: Data Definition Language (DDL)": databases_and_sql/structured_query_language/3_data_definition_language.md
      - "4: Data Manipulation Language (DML)": databases_and_sql/structured_query_language/4_data_manipulation_language.md
      - "5: Data Constraints": databases_and_sql/structured_query_language/5_data_constraints.md
      - "6: Aggregate Functions": databases_and_sql/structured_query_language/6_aggregate_functions.md
      - "7: JOIN Queries": databases_and_sql/structured_query_language/7_join_queries.md
      - "8: Subqueries": databases_and_sql/structured_query_language/8_subqueries.md
      - "9: Advanced Functions": databases_and_sql/structured_query_language/9_advanced_functions.md
      - "10: Views": databases_and_sql/structured_query_language/10_views.md
    - Set Theory:
      - "0: Welcome": databases_and_sql/set_theory/0_table_of_contents.md


extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocs_quiz:
      auto_number: true