site_name: Open Conduit
site_url: https://www.openconduit.org
repo_url: https://github.com/OpenConduit/curriculum
repo_name: GitHub

theme:
  name: material
  logo: assets/open_conduit.png
  favicon: material/database
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.tabs.link
  palette: 
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to Dark Mode
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to Light Mode
  font:
    text: Roboto
    code: JetBrains Mono

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.arithmatex:
      generic: true

nav:
  - Welcome: 
    - "About Open Conduit": index.md
    - "Contributing": contributing.md
  - Databases and SQL:
    - databases_and_sql/index.md
    - Set Theory:
      - "Welcome": databases_and_sql/set_theory/0_welcome.md
      - "1: defining the Set": databases_and_sql/set_theory/1_defining_the_set.md
      - "2: Elements and Membership": databases_and_sql/set_theory/2_elements_and_membership.md
      - "3: The Bag Problem": databases_and_sql/set_theory/3_the_bag_problem.md
      - "4: Subsets and Supersets": databases_and_sql/set_theory/4_subsets_and_supersets.md
      - "5: Boolean Logic and Predicates": databases_and_sql/set_theory/5_boolean_logic_and_predicates.md
      - "6: The Void and the Unknown": databases_and_sql/set_theory/6_void_and_unknown.md
      - "7: The Difference": databases_and_sql/set_theory/7_the_difference.md
      - "8: The Cartesian Product": databases_and_sql/set_theory/8_the_cartesian_product.md
      - "9: Visualizing Data Relationships": databases_and_sql/set_theory/9_visualizing_data_relationships.md
      - "10: Ordered Tuples and Relations": databases_and_sql/set_theory/10_ordered_tuples_and_relations.md
      - "11: Grouping and Partitions": databases_and_sql/set_theory/11_grouping_and_partitions.md
    - Data Modeling:
      - "Welcome": databases_and_sql/dimensional_modeling/0_welcome.md
      - "1: The Two Worlds": databases_and_sql/dimensional_modeling/1_the_two_worlds.md
      - "2: Denormalization": databases_and_sql/dimensional_modeling/2_denormalization.md
      - "3: The Context (Dimensions)": databases_and_sql/dimensional_modeling/3_the_context.md
      - "4: The Measurement (Facts)": databases_and_sql/dimensional_modeling/4_the_measurement.md
      - "5: The Grain (Granularity)": databases_and_sql/dimensional_modeling/5_the_grain.md
      - "6: The Star Schema": databases_and_sql/dimensional_modeling/6_the_star_schema.md
      - "7: The Snowflake Schema": databases_and_sql/dimensional_modeling/7_the_snowflake_schema.md
    - Structured Query Language:
      - "Welcome": databases_and_sql/structured_query_language/0_welcome.md
      - "1: The Foundation of Querying": databases_and_sql/structured_query_language/1_foundation_of_querying.md
      - "2: Filtering and Sorting": databases_and_sql/structured_query_language/2_filtering_and_sorting.md
      - "3: Row-Level Functions (Scalar)": databases_and_sql/structured_query_language/3_row_level_functions.md
      - "4: Aggregation and Grouping": databases_and_sql/structured_query_language/4_aggregation_and_grouping.md
      - "5: Joining Tables": databases_and_sql/structured_query_language/5_joining_tables.md
      - "6: Set Operators": databases_and_sql/structured_query_language/6_set_operators.md
      - "7: Subqueries and CTEs": databases_and_sql/structured_query_language/7_subqueries_and_ctes.md
      - "8: Window Functions": databases_and_sql/structured_query_language/8_window_functions.md
      - "9: Creating Database Objects": databases_and_sql/structured_query_language/9_creating_database_objects.md
      - "10: Modifying Data": databases_and_sql/structured_query_language/10_modifying_data.md
      - "11: Programmable Objects": databases_and_sql/structured_query_language/11_programmable_objects.md
      - "12: Performance Basics": databases_and_sql/structured_query_language/12_performance_basics.md


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocs_quiz:
      auto_number: true

copyright: >
  Copyright &copy; 2026 Open Conduit  |  Content licensed under <a href="https://creativecommons.org/licenses/by-nc/4.0/">CC-BY-NC-4.0</a>  |  Labs licensed under <a href="https://opensource.org/licenses/MIT">MIT</a>.